-- MySQL Script generated by MySQL Workbench
-- Дс 24 Мау 2019 23:19:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xixledb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xixledb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xixledb` DEFAULT CHARACTER SET utf8 ;
USE `xixledb` ;

-- -----------------------------------------------------
-- Table `xixledb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xixledb`.`Admin` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(32) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `loginStatus` VARCHAR(32) NOT NULL,
  `AdminName` VARCHAR(32) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xixledb`.`OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xixledb`.`OrderDetails` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NOT NULL,
  `productName` VARCHAR(32) NOT NULL,
  `quantity` INT NOT NULL,
  `unitCost` DECIMAL NOT NULL,
  `subtotal` DECIMAL NULL,
  PRIMARY KEY (`orderId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xixledb`.`ShippingInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xixledb`.`ShippingInfo` (
  `shippingId` INT NOT NULL AUTO_INCREMENT,
  `shippingType` VARCHAR(32) NOT NULL,
  `shippingCost` VARCHAR(32) NOT NULL,
  `shippingregionId` INT NOT NULL,
  PRIMARY KEY (`shippingId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xixledb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xixledb`.`Order` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `customerId` INT NOT NULL,
  `dateCreated` VARCHAR(32) NOT NULL,
  `dateShipped` VARCHAR(32) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `OrderDetails_orderId` INT NOT NULL,
  `ShippingInfo_shippingId` INT NOT NULL,
  PRIMARY KEY (`orderId`),
  INDEX `fk_Order_OrderDetails1_idx` (`OrderDetails_orderId` ASC),
  INDEX `fk_Order_ShippingInfo1_idx` (`ShippingInfo_shippingId` ASC),
  CONSTRAINT `fk_Order_OrderDetails1`
    FOREIGN KEY (`OrderDetails_orderId`)
    REFERENCES `xixledb`.`OrderDetails` (`orderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_ShippingInfo1`
    FOREIGN KEY (`ShippingInfo_shippingId`)
    REFERENCES `xixledb`.`ShippingInfo` (`shippingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xixledb`.`ShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xixledb`.`ShoppingCart` (
  `cartId` INT NOT NULL AUTO_INCREMENT,
  `productId` VARCHAR(32) NOT NULL,
  `quantity` INT NOT NULL,
  `creditcartInfo` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`cartId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xixledb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xixledb`.`Customer` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(32) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `loginStatus` VARCHAR(32) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `accountBalance` DECIMAL NOT NULL,
  `Order_orderId` INT NOT NULL,
  `ShoppingCart_cartId` INT NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_Customer_Order1_idx` (`Order_orderId` ASC),
  INDEX `fk_Customer_ShoppingCart1_idx` (`ShoppingCart_cartId` ASC),
  CONSTRAINT `fk_Customer_Order1`
    FOREIGN KEY (`Order_orderId`)
    REFERENCES `xixledb`.`Order` (`orderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_ShoppingCart1`
    FOREIGN KEY (`ShoppingCart_cartId`)
    REFERENCES `xixledb`.`ShoppingCart` (`cartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
